from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Optional

from pydantic import validator, Field, model_validator
from pydantic_settings import BaseSettings
from dotenv import load_dotenv

from .exceptions import ConfigurationError


class AppConfig(BaseSettings):
    """Application configuration with validation."""

    # Video Source Selection
    pexels_yn: str = Field("Y", description="Y/N flag for Pexels as a primary video source")
    youtube_yn: str = Field("N", description="Y/N flag for YouTube as a primary video source")
    
    # Pexels Configuration
    pexels_api_key: str = Field("", description="Pexels API key")
    pexels_query: str = Field("nature,landscape,travel", description="Search query for Pexels videos")
    pexels_per_page: int = Field(20, ge=1, le=80, description="Number of videos per page")

    # YouTube Configuration
    youtube_api_key: str = Field("", description="YouTube Data API v3 key")
    youtube_query: str = Field("viral shorts", description="Search query for YouTube videos")
    youtube_max_results: int = Field(8, ge=1, le=50, description="Number of YouTube results to fetch")
    youtube_max_duration_seconds: int = Field(60, ge=1, description="Maximum YouTube video duration in seconds")
    youtube_min_like_count: int = Field(2_000_000, ge=0, description="Minimum YouTube like count")
    youtube_format: str = Field("720", description="Max YouTube download quality (e.g. 1080, 720). Set to 0 for best available quality.")
    youtube_cookies_file: str = Field("", description="Path to Netscape cookies.txt for yt-dlp bot bypass (e.g. /tmp/yt_cookies.txt)")

    # Instagram Graph API Configuration
    ig_user_id: str = Field(..., description="Instagram Business/Creator account user ID")
    ig_access_token: str = Field(..., description="Instagram Graph API access token")
    
    # File Paths
    download_dir: str = Field("downloads", description="Directory for downloaded videos")
    posted_state_file: str = Field("posted_videos.json", description="State file path")
    
    # Content Configuration
    caption_theme: str = Field(..., description="Theme for generated captions")
    default_hashtags: str = Field(..., description="Comma-separated default hashtags")
    # Posting Configuration
    max_video_duration_seconds: int = Field(60, ge=1, description="Maximum video duration in seconds")
    min_aspect_ratio: float = Field(0.5, ge=0.1, le=10.0, description="Minimum aspect ratio")
    max_aspect_ratio: float = Field(2.0, ge=0.1, le=10.0, description="Maximum aspect ratio")
    
    # Logging Configuration
    log_level: str = Field("INFO", description="Logging level")
    log_file: str = Field("", description="Optional log file path")

    # SQLite video ID dedup store — persisted on Railway Volume at /data
    video_id_db: str = Field("/data/videos.db", description="SQLite DB path for posted video IDs (use /data/videos.db on Railway)")

    # Direct video override — when set, skip search and post this YouTube video ID
    video_id: Optional[str] = Field(None, description="YouTube video ID to post directly (bypasses search)")
    youtube_video_id: Optional[str] = Field(None, description="YouTube video ID to post directly (alias for VIDEO_ID; takes priority)")

    # YouTube published-date filter — skip videos older than this date (DD-MM-YYYY)
    check_published_date: Optional[str] = Field(None, description="Only include YouTube videos published on or after this date (DD-MM-YYYY)")

    # Remote State Sync (GitHub Gist) — for GitHub Actions / Render free tier
    # When both are set the state file is pulled from the Gist at startup
    # and pushed back after every run, giving free persistent storage.
    gh_pat: Optional[str] = Field(None, description="GitHub PAT with gist scope (env var: GH_PAT)")
    state_gist_id: Optional[str] = Field(None, description="GitHub Gist ID for state storage")

    # Google Drive video hosting — when set, videos are uploaded to Drive
    # and the public download URL is passed to Instagram instead of transfer.sh.
    google_drive_folder_id: str = Field("", description="Google Drive folder ID for video hosting")
    google_drive_token_file: str = Field("token.json", description="Path to token.json generated by the OAuth auth flow")
    google_drive_upload_yn: str = Field("Y", description="Y/N flag to enable Google Drive upload (set N to skip Drive and use free services directly)")
    
    class Config:
        env_file = '.env'
        case_sensitive = False
        extra = 'ignore'  # Ignore extra fields in .env
        
    @validator('ig_access_token')
    def validate_ig_access_token(cls, v: str) -> str:
        """Validate Instagram access token is present."""
        if not v or len(v) < 10:
            raise ValueError('IG_ACCESS_TOKEN must be a valid Instagram Graph API token')
        return v

    @validator('ig_user_id')
    def validate_ig_user_id(cls, v: str) -> str:
        """Validate Instagram user ID is numeric."""
        if not v or not v.strip().isdigit():
            raise ValueError('IG_USER_ID must be a numeric Instagram account ID')
        return v.strip()

    @validator('pexels_yn', 'youtube_yn')
    def validate_source_flag(cls, v: str) -> str:
        """Validate Y/N source flags."""
        normalized = (v or "").strip().upper()
        if normalized not in {"Y", "N"}:
            raise ValueError("Source flags must be either Y or N")
        return normalized
    
    @validator('min_aspect_ratio', 'max_aspect_ratio')
    def validate_aspect_ratios(cls, v: float, values: dict) -> float:
        """Validate aspect ratio values."""
        if 'min_aspect_ratio' in values and v < values['min_aspect_ratio']:
            raise ValueError('max_aspect_ratio must be greater than min_aspect_ratio')
        return v
    
    @model_validator(mode='after')
    def validate_video_source_config(self) -> 'AppConfig':
        """Validate that at least one primary source is enabled and usable."""
        if self.pexels_yn != "Y" and self.youtube_yn != "Y":
            raise ValueError("At least one video source flag must be Y")

        if self.pexels_yn == "Y" and len((self.pexels_api_key or "").strip()) < 10:
            raise ValueError("PEXELS_API_KEY must be set when PEXELS_YN=Y")

        if self.youtube_yn == "Y" and len((self.youtube_api_key or "").strip()) < 10:
            raise ValueError("YOUTUBE_API_KEY must be set when YOUTUBE_YN=Y")

        return self
    
    @validator('log_level')
    def validate_log_level(cls, v: str) -> str:
        """Validate log level."""
        valid_levels = {'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'}
        if v.upper() not in valid_levels:
            raise ValueError(f'Log level must be one of: {", ".join(valid_levels)}')
        return v.upper()
    
    @property
    def video_id_db_path(self) -> Path:
        """Get SQLite DB path as Path object."""
        p = Path(self.video_id_db)
        return p if p.is_absolute() else Path.cwd() / p

    @property
    def download_dir_path(self) -> Path:
        """Get download directory as Path object (absolute or cwd-relative)."""
        p = Path(self.download_dir)
        return p if p.is_absolute() else Path.cwd() / p

    @property
    def posted_state_file_path(self) -> Path:
        """Get posted state file as Path object (absolute or cwd-relative)."""
        p = Path(self.posted_state_file)
        return p if p.is_absolute() else Path.cwd() / p

    @property
    def log_file_path(self) -> Path | None:
        """Get log file as Path object if specified (absolute or cwd-relative)."""
        if self.log_file:
            p = Path(self.log_file)
            return p if p.is_absolute() else Path.cwd() / p
        return None
    
    @property
    def default_hashtags_list(self) -> List[str]:
        """Parse default hashtags from comma-separated string."""
        return [tag.strip() for tag in self.default_hashtags.split(',') if tag.strip()]

    @property
    def check_published_date_dt(self) -> Optional[datetime]:
        """Parse CHECK_PUBLISHED_DATE (DD-MM-YYYY) into a datetime, or None if unset."""
        raw = (self.check_published_date or "").strip().strip("'\"")
        if not raw:
            return None
        try:
            return datetime.strptime(raw, "%d-%m-%Y")
        except ValueError:
            return None
    
    @property
    def youtube_queries_list(self) -> List[str]:
        """Parse YOUTUBE_QUERY into a list. Accepts [q1, q2] bracket format or plain string."""
        raw = (self.youtube_query or "").strip()
        if raw.startswith('[') and raw.endswith(']'):
            queries = [q.strip() for q in raw[1:-1].split(',') if q.strip()]
            return queries or [self.pexels_query]
        return [raw] if raw else [self.pexels_query]

    @property
    def youtube_query_value(self) -> str:
        """First query in the list — used as a single-query fallback."""
        queries = self.youtube_queries_list
        return queries[0] if queries else self.pexels_query

    @property
    def video_source_order(self) -> List[str]:
        """Return only sources explicitly enabled with Y flag."""
        flags = {
            "pexels": self.pexels_yn,
            "youtube": self.youtube_yn,
        }
        has_config = {
            "pexels": len((self.pexels_api_key or "").strip()) >= 10,
            "youtube": len((self.youtube_api_key or "").strip()) >= 10,
        }

        return [name for name, flag in flags.items() if flag == "Y" and has_config[name]]


def load_config() -> AppConfig:
    """
    Load and validate application configuration.
    
    Returns:
        Validated AppConfig instance
        
    Raises:
        ConfigurationError: If configuration is invalid or missing
    """
    try:
        load_dotenv()
        return AppConfig()
    except Exception as e:
        raise ConfigurationError(f"Failed to load configuration: {e}") from e
